default_config:

logger:
  default: info
  logs:
    custom_components.journey: debug
    homeassistant.loader: error
    homeassistant.setup: error
    homeassistant.helpers.location: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

input_text:
  destination:

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1/32

demo:
