logger:
  default: info
  logs:
    custom_components.journey: debug
    homeassistant.loader: error
    homeassistant.setup: error
    homeassistant.helpers.location: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

config:

history:

logbook:

input_text:
  destination:
    name: MDA Destination
    initial: "home"

mqtt:
  - device_tracker:
      name: "michael"
      state_topic: "location/michael"

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1/32

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - ::1
